clc;
clear all;
data = load('all1.txt');
% t = data.t;
% q = data.q;
t = data(:, 1);

% % 画图
% figure,
% % plot(t,q'*180/pi)
% plot(t, q(1,:) , 'r', ...
%      t, q(2,:), 'g', ...
%      t, q(3,:), 'b', ...
%      t, q(4,:), 'c', ...
%      t, q(5,:), 'm', ...
%      t, q(6,:), 'y', ...
%      t, q(7,:), 'k','LineWidth', 1.0);
% title('激励轨迹关节角度曲线'); xlabel('时间(s)'); ylabel('角度(rad)');
% legend('关节1', '关节2','关节3', '关节4','关节5', '关节6','关节17');

% 画图
figure,
% plot(t,q*180/pi)
plot(t, data(:, 2)*180/pi, 'r', ...
     t, data(:, 3)*180/pi, 'g', ...
     t, data(:, 4)*180/pi, 'b', ...
     t, data(:, 5)*180/pi, 'c', ...
     t, data(:, 6)*180/pi, 'm', ...
     t, data(:, 7)*180/pi, 'y', ...
     t, data(:, 8)*180/pi, 'k','LineWidth', 1.0);
title('激励轨迹关节角度曲线'); xlabel('时间(s)'); ylabel('角度(rad)');
legend('关节1', '关节2','关节3', '关节4','关节5', '关节6','关节17');